version: '3.2'
services:
     changedetection:
          image: ghcr.io/dgtlmoon/changedetection.io:0.47.03
          container_name: changedetection
          hostname: changedetection
          volumes:
               - changedetection-data:/datastore
          environment:
               - PORT=3001
               #Respect proxy_pass type settings, `proxy_set_header Host "localhost";` and `proxy_set_header X-Forwarded-Prefix /app;`
               #More here https://github.com/dgtlmoon/changedetection.io/wiki/Running-changedetection.io-behind-a-reverse-proxy-sub-directory
               # - BASE_URL=https://servicios-ging.dit.upm.es/wachete/
               # Respect proxy_pass type settings, `proxy_set_header Host "localhost";` and `proxy_set_header X-Forwarded-Prefix /app;`
               - USE_X_SETTINGS=1
          ports:
               - 3001:3001


          networks:
               - martell
          restart: unless-stopped

volumes:
     changedetection-data:


networks:
     martell:
          external: true
          name: martell
