services:
    changedetection:
      # https://github.com/dgtlmoon/changedetection.io/releases/tag/0.49.14
      image: ghcr.io/dgtlmoon/changedetection.io:0.49.14
      container_name: changedetection
      hostname: changedetection
      volumes:
        - ./datastore:/datastore
      environment:
        - PORT=3001
        - USE_X_SETTINGS=1
  #       Uncomment below and the "sockpuppetbrowser" to use a real Chrome browser (It uses the "playwright" protocol)
        # - BASE_URL=https://servicios-ging.dit.upm.es/wachete/
        - PLAYWRIGHT_DRIVER_URL=ws://browser-sockpuppet-chrome:3000
  #       Alternative WebDriver/selenium URL, do not use "'s or 's! (old, deprecated, does not support screenshots very well)
        - WEBDRIVER_URL=http://browser-selenium-chrome:4444/wd/hub
        - TZ=Europe/Madrid

      # Comment out ports: when using behind a reverse proxy , enable networks: etc.
      ports:
        - 3001:3001
      networks:
        - martell
      restart: unless-stopped

      depends_on:
         browser-selenium-chrome:
             condition: service_started


    browser-sockpuppet-chrome:
        hostname: browser-sockpuppet-chrome
        image: dgtlmoon/sockpuppetbrowser:0.0.1
        cap_add:
            - SYS_ADMIN
  # SYS_ADMIN might be too much, but it can be needed on your platform https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md#running-puppeteer-on-gitlabci
        restart: unless-stopped
        environment:
            - SCREEN_WIDTH=1920
            - SCREEN_HEIGHT=1024
            - SCREEN_DEPTH=16
            - MAX_CONCURRENT_CHROME_PROCESSES=10
        networks:
            - martell

    browser-selenium-chrome:
        hostname: browser-selenium-chrome
        image: seleniarm/standalone-chromium:4.0.0-20211213
        environment:
            - VNC_NO_PASSWORD=1
            - SCREEN_WIDTH=1920
            - SCREEN_HEIGHT=1080
            - SCREEN_DEPTH=24
        volumes:
            # Workaround to avoid the browser crashing inside a docker container
            # See https://github.com/SeleniumHQ/docker-selenium#quick-start
            - /dev/shm:/dev/shm
        restart: unless-stopped
        networks:
            - martell
networks:
     martell:
          external: true
          name: martell